apiVersion: v1
kind: Service
metadata:
  name: keypouch-backend-service
  namespace: keypouch
  labels:
    app: keypouch
    component: backend
spec:
  selector:
    app: keypouch
    component: backend
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  type: LoadBalancer
