apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: keypouch
  labels:
    app: keypouch
    component: database
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: keypouch
    component: database
  type: ClusterIP
