apiVersion: v1
kind: ConfigMap
metadata:
  name: keypouch-configmap
  namespace: keypouch
data:
  AUTO_HTTPS_ENABLED: 'true'
  DEFAULT_URL_PROTOCOL: https
  URL_DOMAIN_REGEX: ^(www\.|http:\/\/)
  REACT_APP_API_URL: /api
  VITE_API_URL: /api
  REACT_APP_APP_NAME: KeyPouch Directory
  CHOKIDAR_USEPOLLING: 'true'
  WSS_SOCKET_PORT: '443'
  WSS_SOCKET_PATH: /
  PORT: '5001'
  DB_HOST: keypouch-database
  DB_PORT: '5432'
  DB_NAME: keypouch
  DB_USER: admin
  POSTGRES_USER: admin
  POSTGRES_DB: keypouch
